/* Generated by cbindgen from the `ember` crate. Do not edit by hand. */

#ifndef EMBER_H
#define EMBER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Opaque handles. Create with ember_*_new; release with the matching ember_*_free.
 * All calls must occur on the thread that created the ember_app. */
typedef struct ember_signal_i64 ember_signal_i64;
typedef struct ember_label ember_label;
typedef struct ember_button ember_button;
typedef struct ember_stack ember_stack;
typedef struct ember_app ember_app;

/* Library version string (static, do not free). */
const char *ember_version(void);

/* Last error message on this thread, or NULL. Valid until the next failing
 * call on the same thread. Do not free. */
const char *ember_last_error(void);

/* --- i64 signal --- */
ember_signal_i64 *ember_signal_i64_new(int64_t initial);
int64_t ember_signal_i64_get(const ember_signal_i64 *sig);
void ember_signal_i64_set(const ember_signal_i64 *sig, int64_t value);
void ember_signal_i64_free(ember_signal_i64 *sig);

/* --- label --- */
ember_label *ember_label_new(const char *text);
void ember_label_set_text(const ember_label *label, const char *text);
/* Binds the label's text to a signal, rendered as "<prefix><value><suffix>".
 * Applies the current value immediately, then updates on every change. */
void ember_label_bind_i64(const ember_label *label,
                       const ember_signal_i64 *sig,
                       const char *prefix,
                       const char *suffix);
void ember_label_free(ember_label *label);

/* --- button --- */
ember_button *ember_button_new(const char *title);
/* Registers a tap handler; user_data is passed back to cb on each tap. */
void ember_button_on_tap(const ember_button *button,
                      void (*cb)(void *user_data),
                      void *user_data);
void ember_button_free(ember_button *button);

/* --- stack --- */
ember_stack *ember_vstack_new(int spacing);
ember_stack *ember_hstack_new(int spacing);
void ember_stack_push_label(const ember_stack *stack, const ember_label *label);
void ember_stack_push_button(const ember_stack *stack, const ember_button *button);
void ember_stack_free(ember_stack *stack);

/* --- app --- */
/* Creates the app from a root stack (consumed) and a screen size. */
ember_app *ember_app_new(ember_stack *root, int width, int height);
/* Renders one frame. Returns 0 on success, -1 on error (see ember_last_error). */
int ember_app_render_frame(ember_app *app);
/* Dispatches a tap at (x, y) in screen pixels. Returns 1 if a handler ran. */
int ember_app_tap_at(ember_app *app, int x, int y);
void ember_app_free(ember_app *app);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* EMBER_H */
